// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtSUVga4pu5T2TbbrS-t0WUB40HZ_sL8U',
    appId: '1:885295981619:web:d5a895c6ab5bca48e5ef46',
    messagingSenderId: '885295981619',
    projectId: 'danentang-f56be',
    authDomain: 'danentang-f56be.firebaseapp.com',
    storageBucket: 'danentang-f56be.appspot.com',
    measurementId: 'G-M6EJ8EJMVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydVKOpdBwyE48OXNaG0Ela4qCJzPV0M0',
    appId: '1:885295981619:android:3f80526e74467f08e5ef46',
    messagingSenderId: '885295981619',
    projectId: 'danentang-f56be',
    storageBucket: 'danentang-f56be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJckrxRY1y9Wd1uHCGrOs0Yu2UxOMnMM',
    appId: '1:885295981619:ios:fa62c0f389c1d377e5ef46',
    messagingSenderId: '885295981619',
    projectId: 'danentang-f56be',
    storageBucket: 'danentang-f56be.appspot.com',
    iosBundleId: 'com.example.danentang',
  );
}
